#!/usr/bin/env bash
# Get a list of all processes
processes=$(ps aux)

# Filter the list to only show processes that are running
filtered_processes=$(echo "$processes" | grep -v grep)

# Display the list of processes in a user-oriented format
echo "$filtered_processes"

# Show the process hierarchy
pstree "$filtered_processes"
